### ISSUE TITLE
Buff Destroyer

### ISSUE THREAD

**Issue by OZETobi** [Team-OZE/LegionTD-Map#16] opened 2021-01-11 06:15 UTC
**Is your feature request related to a problem? Please describe.**
Destroyer is supposed to be a strong early-game roll. Currently it's a bit too weak.

**Describe the solution you'd like**
Buff HP to 1500 instead of 1300.

**Comment by OZETobi** [comment] 2021-01-16 12:27
1550* instead of 1500.

**Comment by STOPTHECOUNT** [comment] 2021-01-28 19:09
Done. Duplicate of #37.

**Closed by STOPTHECOUNT** 2021-01-28 19:09 UTC
Labels: balance, good first issue
